name: Patch tags

on: [push]

jobs:
  patch:
    name: patch-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: benjlevesque/k8s-portal
          token: ${{ secrets.GH_PAT }}
      - name: Patch
        uses: benjlevesque/patch-tag@master
        with:
          tag: $(git rev-parse --short=8 ${{ github.sha }})
          target: portal-api/values.yaml
          path: sync.image
      - name: Commit files
        run: |
          SHA=$(git rev-parse --short=8 ${{ github.sha }})
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b patch/${SHA}
          git commit -m "Add changes" -a
           git push --set-upstream origin patch/${SHA}
