name: Patch tags

on: [push]
env:
  SHORTSHA: $(git rev-parse --short=8 ${{ github.sha }})

jobs:
  patch:
    name: patch-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: benjlevesque/k8s-portal
          token: ${{ secrets.GH_PAT }}
      - name: Patch
        uses: benjlevesque/patch-tag@master
        with:
          tag: ${{ SHORTSHA }}
          target: portal-api/values.yaml
          path: sync.image
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b patch/${{ SHORTSHA }}
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repository: benjlevesque/k8s-portal
          branch: patch/${{ SHORTSHA }}
