name: Patch tags

on: [push]
jobs:
  patch:
    name: patch-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: benjlevesque/k8s-portal
          token: ${{ secrets.GH_PAT }}
      - name: get shortsha
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
      - name: Patch
        uses: benjlevesque/patch-tag@master
        with:
          tag: ${{ steps.vars.outputs.sha_short }}
          target: portal-api/values.yaml
          path: sync.image
      - name: Commit files
        env:
          SHORTSHA: ${{ steps.vars.outputs.sha_short }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b patch/$SHORTSHA
          git commit -m "Add changes" -a
           git push --set-upstream origin patch/$SHORTSHA
